### PR TITLE
add screenshot function for the agent

### PR DESCRIPTION
**Pull request by xinyu0601**
Add screenshot support.
The code have been tested in nearly 50 phones which has includes phones that are not support by minicap before.

I also try to use libturbojpeg to make compress faster, but failed any way maybe you can helps ^_^ @sorccu 
In real devices one screenshot takes about 300~500ms. While in simulator(eg. iToolsVM, bluestacks) only take 60ms.

Thanks for you great job any way.

### CODE REVIEW

**Comment by sorccu** [comment]
Interesting. It does add a bit of complexity to STF since it would have to handle this alternative way as well. Ideally the output would be compatible with minicap instead of going through zmq. Perhaps it could still be part of the same APK, but runnable as a command like app like the Agent.

By the way do you have a list of devices that don't work?

**Comment by codeskyblue** [comment]
- HTC Desire 816
- Oppo A30

**Comment by codeskyblue** [comment]
Can  it be merged?

**Comment by sorccu** [comment]
I've created issues for those devices in openstf/stf#484 and openstf/stf#485, please post the errors you are seeing. Also please include the output of `adb shell getprop` (remove private information like IP addresses). Also, if possible, run `adb pull /system/lib/libgui.so` and attach it to the issue of that device.

**Comment by sorccu** [comment]
It could be merged but it would also require changes to STF, and if STF has to support many different formats, it'll make it more difficult to improve it later. Do you think you could use https://developer.android.com/reference/android/net/LocalServerSocket.html and make it output the frames in the same format as minicap? That would make it a lot easier to use and require only relatively few changes in STF.

**Comment by sorccu** [comment]
The minicap format is very simple, it's described here: https://github.com/openstf/minicap#usage

**Comment by codeskyblue** [comment]
the two device only reported not supported stf. have to check again. BTW: we still donot know are you interested this pr or not.

**Comment by codeskyblue** [comment]
Because the speed without turbojpeg is very slow. 400ms per screenshot. Is it necessary to start a socket server?

**Comment by sorccu** [comment]
If you make it compatible with minicap, it'll be easier to improve performance later on as a separate unit (perhaps with JNI & libjpeg-turbo)

**Comment by codeskyblue** [comment]
We have tried many days on use JNI & libjpeg-turbo to improve the encode performance. But failed any way. It is not easier for us for we are not very good at C. Really need your help on this part. And we can do the rest.

**Comment by codeskyblue** [comment]
Also I notice that screenshot on STF use command `minicap -s -P ... > /data/local/tmp/screen_xxx.jpg` and pull it from the device, It would be better to use this local java method.

**Comment by sorccu** [comment]
I know it's more work for you to make it behave like minicap, but otherwise
it's more work for me, and I just don't have that much time. If you can
make it work like minicap, then we have a real chance at getting it
integrated with stf fairly quickly.

**Comment by codeskyblue** [comment]
sure we  can do this part.

**Pull request closed without merging**
